EMOTIONS = {
    "Sadness": [
        "Sadness",
        "Grief",
        "Despair",
        "Loneliness",
        "Isolation",
        "Hopelessness",
        "Worthless",
        "Helpless",
    ],
    "Boredom": [
        "Boredom",
        "Apathy",
        "Empty",
        "Indifferent",
        "Unfocused",
        "Tired",
    ],
    "Shame": [
        "Shame",
        "Humiliated",
        "Embarrassed",
        "Ashamed",
        "Guilty",
        "Remorseful",
    ],
    "Fear": [
        "Fear",
        "Scared",
        "Frightened",
        "Anxious",
        "Terrified",
        "Panic",
        "Worried",
        "Apprehensive",
        "Out of Control",
        "Fragile",
        "Vulnerable",
    ],
    "Anger": [
        "Anger",
        "Rage",
        "Fury",
        "Hostile",
        "Furious",
        "Mad",
        "Infuriated",
        "Annoyed",
        "Frustrated",
        "Resentful",
        "Bitter",
        "Indignant",
    ],
    "Disgust": [
        "Disgust",
        "Disgusted",
        "Repelled",
        "Revulsion",
        "Nauseated",
        "Detestable",
    ],
    "Contentment": [
        "Contentment",
        "Peaceful",
        "Relaxed",
        "Satisfied",
        "Secure",
    ],
    "Love": [
        "Love",
        "Loving",
        "Trusting",
        "Intimate",
        "Affectionate",
    ],
    "Joy": [
        "Joy",
        "Happy",
        "Joyful",
        "Excited",
        "Playful",
        "Energetic",
    ],
    "Hope": [
        "Hope",
        "Optimistic",
        "Inspired",
        "Hopeful",
    ],
    "Neutral": [
        "Neutral",
        "Sleepy",
        "Surprised",
        "Astonished",
        "Amazed",
        "Curious",
        "Interested",
    ],
    "Cognitive": [
        "Cognitive",
        "Perplexed",
        "Confused",
        "Critical",
        "Skeptical",
        "Disapproving",
        "Judgmental",
    ],
    "Social": [
        "Social",
        "Rejected",
        "Excluded",
        "Distant",
        "Withdrawn",
        "Numb",
        "Accepted",
        "Respected",
        "Valued",
    ],
    "Motivational": [
        "Motivational",
        "Eager",
        "Pressured",
        "Busy",
        "Rushed",
        "Creative",
    ],
    "Behavioral": [
        "Behavioral",
        "Withdrawn",
        "Critical",
        "Aroused",
    ],
}
